@GameApi_HostAddress = http://localhost:5002

GET {{GameApi_HostAddress}}/api/games
Accept: application/json

###
GET {{GameApi_HostAddress}}/weatherforecast
Accept: application/json
###

POST {{GameApi_HostAddress}}/api/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "genre": "Action-Adventure",
  "releaseDate": "2017-03-03T00:00:00",
  "description": "Open-world adventure in Hyrule."
}

###

POST {{GameApi_HostAddress}}/api/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Sandbox",
  "releaseDate": "2011-11-18T00:00:00",
  "description": "Creative building and survival gameplay."
}

###

POST {{GameApi_HostAddress}}/api/games
Content-Type: application/json

{
  "name": "Elden Ring",
  "genre": "Action RPG",
  "releaseDate": "2022-02-25T00:00:00",
  "description": "Dark fantasy RPG with open-world exploration."
}

###
